package cn.labhomework.dataobject;

import java.util.Date;

public class LoginLogDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginLog.id
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginLog.date
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginLog.relatestuid
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    private Integer relatestuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginLog.id
     *
     * @return the value of LoginLog.id
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginLog.id
     *
     * @param id the value for LoginLog.id
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginLog.date
     *
     * @return the value of LoginLog.date
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginLog.date
     *
     * @param date the value for LoginLog.date
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginLog.relatestuid
     *
     * @return the value of LoginLog.relatestuid
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    public Integer getRelatestuid() {
        return relatestuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginLog.relatestuid
     *
     * @param relatestuid the value for LoginLog.relatestuid
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    public void setRelatestuid(Integer relatestuid) {
        this.relatestuid = relatestuid;
    }
}