package cn.labhomework.dataobject;

public class StudentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.id
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.name
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.gender
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.password
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.IDNumber
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    private Integer idnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.id
     *
     * @return the value of Student.id
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.id
     *
     * @param id the value for Student.id
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.name
     *
     * @return the value of Student.name
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.name
     *
     * @param name the value for Student.name
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.gender
     *
     * @return the value of Student.gender
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.gender
     *
     * @param gender the value for Student.gender
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.password
     *
     * @return the value of Student.password
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.password
     *
     * @param password the value for Student.password
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.IDNumber
     *
     * @return the value of Student.IDNumber
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    public Integer getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.IDNumber
     *
     * @param idnumber the value for Student.IDNumber
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    public void setIdnumber(Integer idnumber) {
        this.idnumber = idnumber;
    }
}