package cn.labhomework.dao;

import cn.labhomework.dataobject.LoginLogDO;

import java.util.List;

public interface LoginLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginLog
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginLog
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    int insert(LoginLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginLog
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    int insertSelective(LoginLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginLog
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    LoginLogDO selectByPrimaryKey(Integer id);

    List<LoginLogDO> selectByRelateId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginLog
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    int updateByPrimaryKeySelective(LoginLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginLog
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    int updateByPrimaryKey(LoginLogDO record);
}