package cn.labhomework.dao;

import cn.labhomework.dataobject.StudentDO;

public interface StudentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    int insert(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    int insertSelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    StudentDO selectByPrimaryKey(Integer id);

    StudentDO selectByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    int updateByPrimaryKeySelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Fri Sep 13 21:28:52 CST 2019
     */
    int updateByPrimaryKey(StudentDO record);
}